django_logbox/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
django_logbox/admin.py,sha256=SZfuinXo3--z4y1dEBkSCLW5BIQhSE4JT_et80XrFtc,2135
django_logbox/app_settings.py,sha256=aJ_Yx4C-heG-vjw6xF88d5tDdTC23YmaXahWPHx3kSA,1714
django_logbox/apps.py,sha256=5CaHPyN3Zoa35CN9TkaidibGUXcYd0ge3rA1AocA2gw,243
django_logbox/locale/ko_KR/LC_MESSAGES/django.mo,sha256=jBgRriBGmvMappVjw0wu2McHhDtD9uDWiQdskcWl2qs,2954
django_logbox/locale/ko_KR/LC_MESSAGES/django.po,sha256=hwXMKIEOZfPk_zHAr6JKp3EbL9UrCmZJSuCkU37bDR4,4058
django_logbox/middlewares.py,sha256=HfgCx7R8GppSNjxaw9JvWHxJhLYk1NECCXhxCThxkwQ,2728
django_logbox/migrations/0001_initial.py,sha256=6VT2pvAYWeTYYkxWm9XFi30U8cE-xJGADTvwQucEgqg,1999
django_logbox/migrations/0002_remove_serverlog_duration.py,sha256=1Xz2hUND59e31opN7LqflRS8Jm3JFZOKP4VJvxBEWnE,327
django_logbox/migrations/0003_rename_exception_serverlog_exception_type_and_more.py,sha256=LHYtGqdFWGwdgXMMKYJKtwcfMe23DI8pkAkK3_lc7JM,592
django_logbox/migrations/0004_alter_serverlog_client_ip_and_more.py,sha256=YmJjhVqFmQHBAQaKtJTH3ysIe7LjXRJ-oMNnfvIFpck,4123
django_logbox/migrations/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
django_logbox/models.py,sha256=CDkc2cG97cMRFcX6lNdzs_RLafz1-sh9U5IdcoEXIrA,2555
django_logbox/threading.py,sha256=i01ejF6_blNYd3wp_X6E9nZsZxo8ufGdyQJJwx8SRsA,2053
django_logbox/utils.py,sha256=nqxhuB6-PrhDu-jhHy6F6fSlmo1ozUyQ1_ywJaziLxM,2541
django_logbox-0.0.10.dist-info/METADATA,sha256=c4QOGy-R9XZzQdhXyiF-9ZnF097UW5TkWH_M2-P320E,2998
django_logbox-0.0.10.dist-info/WHEEL,sha256=Nq82e9rUAnEjt98J6MlVmMCZb-t9cYE2Ir1kpBmnWfs,88
django_logbox-0.0.10.dist-info/RECORD,,
