

exec('1+1')
#*WARNING* 30.py:3: unresolved call to 'exec'
